version: '3.8'

services:
  # Sample web application
  nginx-app:
    image: nginx:alpine
    container_name: sample-nginx
    ports:
      - "8080:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    logging:
      driver: json-file
      options:
        max-size: "10m"
        max-file: "3"
    labels:
      - "logging=enabled"

  # Sample API application
  api-app:
    image: node:alpine
    container_name: sample-api
    command: sh -c "while true; do echo '{\"timestamp\":\"$(date -Iseconds)\",\"level\":\"info\",\"message\":\"API request processed\",\"response_time\":$(shuf -i 10-500 -n 1)}'; sleep $(shuf -i 1-10 -n 1); done"
    logging:
      driver: json-file
      options:
        max-size: "10m"
        max-file: "3"
    labels:
      - "logging=enabled"

  # Sample database application
  db-app:
    image: postgres:alpine
    container_name: sample-db
    environment:
      POSTGRES_DB: testdb
      POSTGRES_USER: testuser
      POSTGRES_PASSWORD: testpass
    logging:
      driver: json-file
      options:
        max-size: "10m"
        max-file: "3"
    labels:
      - "logging=enabled"